//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS_SYSTEM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISSUEBOOK
    {
        public int IssueID { get; set; }
        public string IssueDate { get; set; }
        public string ExpiryDate { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<int> CustomerId { get; set; }
    
        public virtual BOOK BOOK { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
    }
}
