//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS_SYSTEM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STAFF()
        {
            this.RETURNBOOKs = new HashSet<RETURNBOOK>();
        }
    
        public int StaffID { get; set; }
        public string StaffName { get; set; }
        public string StaffEmail { get; set; }
        public string StaffAddress { get; set; }
        public string StaffGender { get; set; }
        public Nullable<int> StaffPhone { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        public virtual BRANCH BRANCH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RETURNBOOK> RETURNBOOKs { get; set; }
    }
}
